config/routes.rb
Rails.application.routes.draw do

  resources :accounts

  devise_for :users, :path_prefix => 'my'
  resources :users
  devise_scope :user do
    get '/logout' => "devise/sessions#destroy"
    get '/login' => "devise/sessions#new"
    get '/sign_up' => "accounts#new"
    get '/profile' => "devise/registrations#edit"
  end

  get '/dashboard', :to => "home#dashboard", :as => :dashboard
  get '/upcoming_washes', :to => "home#upcoming_washes", :as => :upcoming_washes

  root :to => 'home#index'

end

app/models/account.rb
class Account
  include Mongoid::Document
  field :subdomain, type: String
  field :company, type: String
  field :phone, type: String
  field :email, type: String

  has_many :users, dependent: :destroy
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable

  #role
  field :role,                 :type => String, default: "crew"

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  belongs_to :account
  before_destroy :user_is_admin?

  class << self
    def columns
      self.fields.collect{|c| c[1]}
    end

    def role_list
      %w{crew admin}
    end
  end

  private
  def user_is_admin?
    #code
    errors.add :base, "Cannot Remove An Administrator" if is_admin?
    errors.blank
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @accounts = Account.all
    respond_with(@accounts)
  end

  def show
    respond_with(@account)
  end

  def new
    sign_out(current_user) if current_user
    @account = Account.new
    @account.users.build(role: "admin")
    respond_with(@account)
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.save
    respond_with(@account)
  end

  def update
    @account.update(account_params)
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:subdomain, :company, :phone, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    layout :layout_by_resource
    # helper
    helper_method :current_account

    def layout_by_resource
        if !devise_controller? || (controller_name == "registrations" && action_name == "edit")
          "application"
        else
          "devise_layout"
        end
    end

    protected

    def set_current_account
      @current_account = Account.where(:subdomain => request.subdomain).first
      if @current_account.present?
        # Mongoid::Multitenancy.current_tenant = @current_account
      else
        render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found  if request.subdomain != "www"
      end
    end

    def current_account
      @current_account
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def dashboard
  end

  def upcoming_washes
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for @account, html: {class: "form-vertical"}, remote: false do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company, required: true, :input_html => {placeholder: "Company Name"}, label: false %>

    <%= f.simple_fields_for :users do |u| %>
        <%= u.input :email, required: true, :input_html => {placeholder: "Your Email Address"}, label: false %>
        <%= u.input :password, required: true, :input_html => {placeholder: "Your Password"}, label: false %>
        <%= u.input :password_confirmation, required: true, :input_html => {placeholder: "Confirm Your Password"}, label: false %>
    <% end %>
    <%= f.input :subdomain, label: "Site URL", required: false, wrapper: :append do |n| %>
        <%= f.input_field :subdomain %>
        <%= content_tag :span, ".#{SITE_URL}", class: "add-on" %>
    <% end %>


  </div>

  <div class="form-actions">
    <%= f.button :submit, "Create Account", class: 'btn-primary' %>
    <%= link_to "Cancel Account", root_path, class: 'btn' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Subdomain</th>
      <th>Company</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.subdomain %></td>
        <td><%= account.company %></td>
        <td><%= account.phone %></td>
        <td><%= account.email %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h3>Create New account</h3>
<div id="registration_form">
  <%= render 'form' %>
</div>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subdomain:</strong>
  <%= @account.subdomain %>
</p>

<p>
  <strong>Company:</strong>
  <%= @account.company %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @account.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/home/dashboard.html.erb
<h1>Home#dashboard</h1>
<p>Find me in app/views/home/dashboard.html.erb</p>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Super awesome!</h1>
  <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
  <!--<a class="btn btn-large btn-success" href="/sign_up">Sign up today</a>-->
</div>
<hr>

<div class="row-fluid marketing">
  <div class="span6">
    <h4>Subheading</h4>
    <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

    <h4>Subheading</h4>
    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

    <h4>Subheading</h4>
    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
  </div>

  <div class="span6">
    <h4>Subheading</h4>
    <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

    <h4>Subheading</h4>
    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

    <h4>Subheading</h4>
    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
  </div>
</div>

<hr>

app/views/home/upcoming_washes.html.erb
<h1>Home#upcoming_washes</h1>
<p>Find me in app/views/home/upcoming_washes.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Copyfleet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>
<div class="container">
    <div class="row">
        <%= render 'shared/left_menu' %>
        <div class="span7"><%= yield %></div>
        <div class="span3">
          <%= yield(:actions_panel) %>
          <%= yield(:filters) %>
        </div>
    </div>
</div>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/devise_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Copyfleet" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "devise", :media => "all" %>


    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class="login-layout">
    <div class="container-fluid" id="main-container">
			<div id="main-content">
				<div class="row-fluid">
					<div class="span12">
            <div class="login-container">

            <div class="row-fluid">
            	<div class="center">
            		<h1><span class="white">Fleet Clean Lab</span></h1>
            	</div>
            </div>

            <div class="space-6"></div>

            <div class="row-fluid">

            <div class="position-relative">


            	<div id="login-box" class="visible widget-box no-border">

            		<div class="widget-body">
            		 <div class="widget-main">
            			<h4 class="header lighter bigger">Please Enter Your Information</h4>

            			<div class="space-6"></div>

            			<%= yield %>
            		 </div><!--/widget-main-->


            		 <div class="toolbar clearfix">
            			<div>
            				<a href="#" onclick="show_box('forgot-box'); return false;" class="forgot-password-link"><i class="icon-arrow-left"></i> I forgot my password</a>
            			</div>
            			<div>

            			</div>
            		 </div>
            		</div><!--/widget-body-->

            	</div><!--/login-box-->






            	<div id="forgot-box" class="widget-box no-border">

            		<div class="widget-body">
            		 <div class="widget-main">
            			<h4 class="header red lighter bigger"><i class="icon-key"></i> Retrieve Password</h4>

            			<div class="space-6"></div>

            			<p>
            				Enter your email and to receive instructions
            			</p>
            			<form accept-charset="UTF-8" action="/my/users/password" class="simple_form new_user" id="new_user_password" method="post" novalidate="novalidate"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="fGMlsWslToGdWcuOsAITScePV6IdFGihyOPKJZXpd0o="></div>
                    <fieldset>
            					<label>
            						<span class="block input-icon input-icon-right">
            							<input type="email" class="span12" placeholder="Email" id="user_email" name="user[email]" />
            							<i class="icon-envelope"></i>
            						</span>
            					</label>

            					<div class="row-fluid">
            						<button class="span5 offset7 btn btn-small btn-danger"><i class="icon-lightbulb"></i> Send Me!</button>
            					</div>

            				  </fieldset>
                  </form>
            		 </div><!--/widget-main-->


            		 <div class="toolbar center">
            			<a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">Back to login <i class="icon-arrow-right"></i></a>
            		 </div>
            		</div><!--/widget-body-->

            	</div><!--/forgot-box-->







            </div><!--/position-relative-->

            </div>


            </div>


					</div><!--/span-->
				</div><!--/row-->
			</div>
		</div><!--/.fluid-container-->


		<!-- basic scripts -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script type="text/javascript">
		window.jQuery || document.write("<script src='assets/js/jquery-1.9.1.min.js'>\x3C/script>");
		</script>


		<!-- page specific plugin scripts -->


		<!-- inline scripts related to this page -->

		<script type="text/javascript">

      function show_box(id) {
       $('.widget-box.visible').removeClass('visible');
       $('#'+id).addClass('visible');
      }

		</script>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%#= custom_bootstrap_flash %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/"><%#= current_account.company if current_account %></a>
      <div class="container nav-collapse ">
        <ul class="nav visible-phone visible-tablet">
          <%= render "shared/menus"%>
        </ul>
        <ul class="nav visible-phone visible-tablet">
          <%# if current_user %>
            <li><%#= current_user.email %></li>
            <li>
              <a href="/profile">Change Password</a>
            </li>
            <li>
              <%#= link_to raw("<i class='icon-off'></i> Logout"), logout_path, class: "sign_out" %>
            </li>
          <%# end %>
        </ul>
        <ul class="nav pull-right hidden-phone hidden-tablet">
          <% if current_user %>
            <li class="dropdown hide-phone">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%#= 'Aulia' %><%= current_user.email %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="/profile">Change Password</a>
                </li>
                <li>
                  <%= link_to raw("<i class='icon-off'></i> Logout"), logout_path, class: "sign_out" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_left_menu.html.erb
<div class="span2 hidden-phone hidden-tablet" >
  <ul id="main-nav" class="nav nav-tabs nav-stacked">
    <%= render "shared/menus" %>
</div>

app/views/shared/_menus.html.erb
<li>
  <a href="/dashboard">
	<i class="icon-dashboard"></i>
	<span>Dashboard</span>
  </a>
</li>
<li>
  <a href="/upcoming_washes">
	<i class="icon-tint"></i>
	<span>Upcoming Washes</span>
  </a>
</li>
<li>
  <a href="/wash_reports">
	<i class="icon-list-alt"></i>
	<span>Wash Reports</span>
  </a>
</li>
<li>
  <a href="/targets">
	<i class="icon-pushpin"></i>
	<span>Targets</span>
  </a>
</li>
<li>
  <a href="/invoices">
	<i class="icon-credit-card"></i>
	<span>Invoices</span>
  </a>
</li>
<li>
  <a href="/customers">
	<i class="icon-user"></i>
	<span>Customers</span>
  </a>
</li>
<li>
  <a href="/tasks">
	<i class="icon-ok"></i>
	<span>Tasks</span>
  </a>
</li>
<li>
  <a href="/schedules">
	<i class="icon-calendar"></i>
	<span>Schedules</span>
  </a>
</li>
<!-- <li>
  <a href="/users">
  <i class="icon-group"></i>
  <span>Users and Roles</span>
  </a>
</li> -->
<li class="notifications_counter">
  <%= render "shared/notifications_menu"%>
</li>
<li>
  <a href="/settings" class="dropdown-toggle" >
	<i class="icon-cog"></i>
	<span>Settings</span>
	</a>
</li>

app/views/shared/_notifications_menu.html.erb
<a href="/notifications" class="dropdown-toggle" >
<%# if current_user && current_user.mailbox.notifications.unread.length > 0 %>
  <span class="badge badge-important">
    <%#= current_user.mailbox.notifications.unread.length%>
  </span>
<%# else %>
  <i class="icon-envelope"></i>
<%# end %>
	<span>
    Notifications
  </span>
</a>